CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Cedula VARCHAR(24) NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(50) UsersNOT NULL,
    FailedLoginAttempts INT NOT NULL DEFAULT 0,
    LockoutEndTime DATETIME NULL,
    CreationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastAccessDate DATETIME NULL
);
